version: '3.9'
services:
  #Node 18.19-alpine web server service
  node-web-server:
    container_name: 'node-web-server'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file: ./.env
