const FIELDS_ABOUT_US_PAGE = `*,cards.CardItem_id.*,coreValues.CardItem_id.*`;
const FIELDS_BANNER = `*`;
const FIELDS_BUTTON = `*`;
const FIELDS_NAVIGATION = `*`;
const FIELDS_CONTACT_FORM = `*`;
const FIELDS_CONTACT_PAGE = `*`;
const FIELDS_FAQ_SECTION = `*`;
const FIELDS_FOOTER = `*`;
const FIELDS_HOW_IT_WORK_SECTION = `*`;
const FIELDS_NAVIGATION_MENU = `*`;
const FIELDS_PRICING_SECTION = `*`;
const FIELDS_SERVICES_SECTION = `*`;

export {
  FIELDS_ABOUT_US_PAGE,
  FIELDS_BANNER,
  FIELDS_BUTTON,
  FIELDS_NAVIGATION,
  FIELDS_CONTACT_FORM,
  FIELDS_CONTACT_PAGE,
  FIELDS_FAQ_SECTION,
  FIELDS_FOOTER,
  FIELDS_HOW_IT_WORK_SECTION,
  FIELDS_NAVIGATION_MENU,
  FIELDS_PRICING_SECTION,
  FIELDS_SERVICES_SECTION,
};
