const ABOUT_US_PAGE_DATA_ID = 1;
const BANNER_DATA_ID = 1;
const BUTTON_DATA_ID = 1;
const CONTACT_FORM_DATA_ID = 1;
const CONTACT_PAGE_DATA_ID = 1;
const FAQ_SECTION_DATA_ID = 1;
const FOOTER_DATA_ID = 1;
const HOW_IT_WORK_SECTION_DATA_ID = 1;
const NAVIGATION_MENU_DATA_ID = 1;
const PRICING_SECTION_DATA_ID = 1;
const SERVICES_SECTION_DATA_ID = 1;

export {
  ABOUT_US_PAGE_DATA_ID,
  BANNER_DATA_ID,
  BUTTON_DATA_ID,
  CONTACT_FORM_DATA_ID,
  CONTACT_PAGE_DATA_ID,
  FAQ_SECTION_DATA_ID,
  FOOTER_DATA_ID,
  HOW_IT_WORK_SECTION_DATA_ID,
  NAVIGATION_MENU_DATA_ID,
  PRICING_SECTION_DATA_ID,
  SERVICES_SECTION_DATA_ID,
};
