@host = https://backoffice.chillo.fr
@token = 7wnlAKIGVv6kpnMyuE4sd3s6zLPam4Ec

### About us page
GET {{host}}/items/AboutUsPage/1?fields=*,cards.CardItem_id.*,coreValues.CardItem_id.*
Content-Type: application/json
Authorization: Bearer {{token}}

### Banner
GET {{host}}/items/Banner/1?fields=*
Content-Type: application/json
Authorization: Bearer {{token}}

### Button
GET {{host}}/items/Button/1?fields=*
Content-Type: application/json
Authorization: Bearer {{token}}

### Navigation Menu
GET {{ host }}/items/NavigationMenu/1?fields=*
Content-Type: application/json
Authorization: Bearer {{ token }}

### Footer
GET {{ host }}/items/footer
Content-Type: application/json
Authorization: Bearer {{ token }}

### How it work section
GET {{ host }}/items/HowItWorkSection/1?fields=*,items.HowItWorkItem_id.*
Content-Type: application/json
Authorization: Bearer {{ token }}

### FAQ Section
GET {{ host }}/items/FAQSection/1?fields=*,items.*
Content-Type: application/json
Authorization: Bearer {{ token }}

### Pricing Section
GET {{ host }}/items/PricingSection/1?fields=*,offers.PricingOffer_id.*.Offer_id.title
Content-Type: application/json
Authorization: Bearer {{ token }}

### Service Section
GET {{ host }}/items/ServiceSection/1?fields=*,topServices.ServiceCard_id.*,services.ServiceCard_id.*
Content-Type: application/json
Authorization: Bearer {{ token }}

### Contact page
GET {{ host }}/items/ContactPage/1?fields=*,form.*,form.fields.*
Content-Type: application/json
Authorization: Bearer {{ token }}
